// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <ATen/hip/ATenHIPGeneral.h>
#include <ATen/hip/HIPContext.h>
#include <ATen/hip/Exceptions.h>
#include <c10/hip/HIPEvent.h>
#include <c10/hip/HIPGuard.h>
