// !!! This is a file automatically generated by hipify!!!
#include <gtest/gtest.h>

#include <c10/hip/impl/HIPTest.h>

using namespace c10::cuda::impl;

TEST(CUDATest, SmokeTest) {
  c10_cuda_test();
}
