// !!! This is a file automatically generated by hipify!!!
#include <c10/hip/impl/HIPGuardImpl.h>

namespace c10::cuda::impl {

C10_REGISTER_GUARD_IMPL(CUDA, CUDAGuardImpl)

} // namespace c10::cuda::impl
